#!/usr/bin/env bun
/**
 * Build script to embed EJS templates as strings in the bundle.
 * This eliminates the need to distribute template files separately.
 */
import * as fs from 'node:fs/promises';
import * as path from 'node:path';

const TEMPLATES_DIR = path.join(import.meta.dir, '../src/templates');
const OUTPUT_FILE = path.join(import.meta.dir, '../src/generators/embedded-templates.ts');

async function findTemplateFiles(dir: string, basePath = ''): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const relativePath = path.join(basePath, entry.name);
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await findTemplateFiles(fullPath, relativePath)));
    } else if (entry.name.endsWith('.ejs')) {
      files.push(relativePath);
    }
  }

  return files;
}

function escapeTemplateString(content: string): string {
  return content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

async function main() {
  const templateFiles = await findTemplateFiles(TEMPLATES_DIR);
  templateFiles.sort();

  const entries: string[] = [];

  for (const file of templateFiles) {
    const fullPath = path.join(TEMPLATES_DIR, file);
    const content = await fs.readFile(fullPath, 'utf-8');
    const escaped = escapeTemplateString(content);
    // Normalize path separators for cross-platform compatibility
    const normalizedPath = file.replace(/\\/g, '/');
    entries.push(`  '${normalizedPath}': \`${escaped}\``);
  }

  const output = `// Auto-generated by scripts/embed-templates.ts
// Do not edit manually

export const EMBEDDED_TEMPLATES: Record<string, string> = {
${entries.join(',\n')},
};
`;

  await fs.writeFile(OUTPUT_FILE, output, 'utf-8');
  console.log(`Generated ${OUTPUT_FILE} with ${templateFiles.length} templates`);
}

main().catch(console.error);
